server:
  port: 8888
  
spring:
  cloud:    config:      server:
          default-label: main          git:            uri: https://github.com/guilhermehr/microservices-repo            search-paths:            - fornecedor
            - loja
            - transportador
            
